# Generated by Django 3.2.16 on 2023-04-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AI_menu_App', '0003_rename_login_help_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ORDER_MAIN',
        ),
        migrations.AddField(
            model_name='payment',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AI_menu_App.customer'),
        ),
    ]
