# Generated by Django 3.2.16 on 2023-04-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AI_menu_App', '0004_auto_20230411_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ORDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AI_menu_App.order_main'),
        ),
    ]
