# Generated by Django 3.2.16 on 2023-04-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_menu_App', '0005_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ORDER',
        ),
    ]
